
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('Tag').del()
    .then(function () {
      // Inserts seed entries
      return knex('Tag').insert(
        [
          {
            "id": 1,
            "tagName": "collection",
            "tagBefore": "",
            "tagAfter": "",
            "model": "datacard",
            "modelAttribute": "catalogue.collection.name",
            "fontSize": "24",
            "fontWeight": "bold",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "center",
            "backgroundColor": "rgba(255, 23, 68, 0.8)",
            "exampleValue": "Colección fotográfica de vertebrados",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 0,
            "w": 90,
            "h": 36,
            "i": "collection",
            "style": null,
            "templateId": 1
          },
          {
            "id": 2,
            "tagName": "photocollect",
            "tagBefore": "",
            "tagAfter": "",
            "model": "",
            "modelAttribute": "",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "#BDBDBD",
            "exampleValue": "906.6 x 644.2",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 22,
            "y": 50,
            "w": 68,
            "h": 636,
            "i": "photocollect",
            "style": null,
            "templateId": 1
          },
          {
            "id": 3,
            "tagName": "instituteLogo",
            "tagBefore": "",
            "tagAfter": "",
            "model": "",
            "modelAttribute": "",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "#BDBDBD",
            "exampleValue": "106.6 x 97.2",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 7,
            "y": 50,
            "w": 8,
            "h": 96,
            "i": "instituteLogo",
            "style": null,
            "templateId": 1
          },
          {
            "id": 4,
            "tagName": "instituteName",
            "tagBefore": "",
            "tagAfter": "",
            "model": "datacard",
            "modelAttribute": "catalogue.collection.instituteName",
            "fontSize": "20",
            "fontWeight": "bold",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "center",
            "backgroundColor": "rgba(230, 81, 0, 0.8)",
            "exampleValue": "Instituto de Investigaciones Biológicas",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 148,
            "w": 21,
            "h": 58,
            "i": "instituteName",
            "style": null,
            "templateId": 1
          },
          {
            "id": 5,
            "tagName": "lifeStage",
            "tagBefore": "",
            "tagAfter": ",",
            "model": "specimen",
            "modelAttribute": "lifeStage.name",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(255, 23, 68, 0.8)",
            "exampleValue": "Juvenil",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 239,
            "w": 7,
            "h": 31,
            "i": "lifeStage",
            "style": null,
            "templateId": 1
          },
          {
            "id": 6,
            "tagName": "sexSymbol",
            "tagBefore": "",
            "tagAfter": "",
            "model": "specimen",
            "modelAttribute": "sex.symbol",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(233, 32, 99, 0.8)",
            "exampleValue": "♀",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 7,
            "y": 239,
            "w": 3,
            "h": 33,
            "i": "sexSymbol",
            "style": null,
            "templateId": 1
          },
          {
            "id": 7,
            "tagName": "DMSLatitude",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "DMSLatitude",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(255, 153, 0, 0.8)",
            "exampleValue": "19° 43' 12''",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 273,
            "w": 15,
            "h": 28,
            "i": "DMSLatitude",
            "style": null,
            "templateId": 1
          },
          {
            "id": 8,
            "tagName": "DMSLongitude",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "DMSLongitude",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(255, 23, 68, 0.8)",
            "exampleValue": "23° 87' 12''",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 303,
            "w": 15,
            "h": 28,
            "i": "DMSLongitude",
            "style": null,
            "templateId": 1
          },
          {
            "id": 9,
            "tagName": "altitude",
            "tagBefore": "",
            "tagAfter": " msnm",
            "model": "collect",
            "modelAttribute": "altitude",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(233, 32, 99, 0.8)",
            "exampleValue": "2000",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 355,
            "w": 12,
            "h": 31,
            "i": "altitude",
            "style": null,
            "templateId": 1
          },
          {
            "id": 10,
            "tagName": "climateType",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "climateType.code",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(255, 153, 0, 0.8)",
            "exampleValue": "A('w)",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 13,
            "y": 355,
            "w": 6,
            "h": 31,
            "i": "climateType",
            "style": null,
            "templateId": 1
          },
          {
            "id": 11,
            "tagName": "vegetationType",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "vegetationType.name",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(230, 81, 0, 0.8)",
            "exampleValue": "Bosque mesófilo",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 389,
            "w": 21,
            "h": 35,
            "i": "vegetationType",
            "style": null,
            "templateId": 1
          },
          {
            "id": 12,
            "tagName": "locality",
            "tagBefore": "",
            "tagAfter": ",",
            "model": "collect",
            "modelAttribute": "locality",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(0, 229, 255, 0.8)",
            "exampleValue": "Coatepec",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 446,
            "w": 11,
            "h": 33,
            "i": "locality",
            "style": null,
            "templateId": 1
          },
          {
            "id": 13,
            "tagName": "municipality",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "municipality",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(255, 23, 68, 0.8)",
            "exampleValue": "Xalapa",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 11,
            "y": 446,
            "w": 10,
            "h": 34,
            "i": "municipality",
            "style": null,
            "templateId": 1
          },
          {
            "id": 14,
            "tagName": "countryState",
            "tagBefore": "",
            "tagAfter": ",",
            "model": "collect",
            "modelAttribute": "countryState",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(0, 176, 255, 0.8)",
            "exampleValue": "Veracruz",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 479,
            "w": 11,
            "h": 28,
            "i": "countryState",
            "style": null,
            "templateId": 1
          },
          {
            "id": 15,
            "tagName": "country",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "country",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(32, 148, 243, 0.8)",
            "exampleValue": "México",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 11,
            "y": 480,
            "w": 10,
            "h": 28,
            "i": "country",
            "style": null,
            "templateId": 1
          },
          {
            "id": 16,
            "tagName": "collectDate",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "formattedCollectDate",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(0, 229, 255, 0.8)",
            "exampleValue": "14/02/2019",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 534,
            "w": 17,
            "h": 30,
            "i": "collectDate",
            "style": null,
            "templateId": 1
          },
          {
            "id": 17,
            "tagName": "collectHour",
            "tagBefore": "",
            "tagAfter": " h",
            "model": "collect",
            "modelAttribute": "formattedCollectHour",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(230, 81, 0, 0.8)",
            "exampleValue": "10:34",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 564,
            "w": 11,
            "h": 29,
            "i": "collectHour",
            "style": null,
            "templateId": 1
          },
          {
            "id": 18,
            "tagName": "device",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "model.device.name",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(32, 148, 243, 0.8)",
            "exampleValue": "motorola",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 616,
            "w": 9,
            "h": 29,
            "i": "device",
            "style": null,
            "templateId": 1
          },
          {
            "id": 19,
            "tagName": "model",
            "tagBefore": "",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "model.name",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(0, 176, 255, 0.8)",
            "exampleValue": "moto g5",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 10,
            "y": 616,
            "w": 9,
            "h": 29,
            "i": "model",
            "style": null,
            "templateId": 1
          },
          {
            "id": 20,
            "tagName": "collector",
            "tagBefore": "Foto: ",
            "tagAfter": "",
            "model": "collect",
            "modelAttribute": "collector.name",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(0, 176, 255, 0.8)",
            "exampleValue": "Alan Yoset Garcia Cruz",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 646,
            "w": 21,
            "h": 30,
            "i": "collector",
            "style": null,
            "templateId": 1
          },
          {
            "id": 21,
            "tagName": "collectorCode",
            "tagBefore": "",
            "tagAfter": "",
            "model": "datacard",
            "modelAttribute": "collectorCode",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(32, 148, 243, 0.8)",
            "exampleValue": "CADA 00001",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 678,
            "w": 12,
            "h": 28,
            "i": "collectorCode",
            "style": null,
            "templateId": 1
          },
          {
            "id": 22,
            "tagName": "instituteAcronym",
            "tagBefore": "",
            "tagAfter": "",
            "model": "datacard",
            "modelAttribute": "catalogue.collection.instituteAcronym",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(233, 32, 99, 0.8)",
            "exampleValue": "IIB-UV",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 0,
            "y": 706,
            "w": 7,
            "h": 29,
            "i": "instituteAcronym",
            "style": null,
            "templateId": 1
          },
          {
            "id": 23,
            "tagName": "scientificName",
            "tagBefore": "",
            "tagAfter": "",
            "model": "species",
            "modelAttribute": "scientificName",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "italic",
            "fontColor": null,
            "textAlignment": "left",
            "backgroundColor": "rgba(233, 32, 99, 0.8)",
            "exampleValue": "Felis catus",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 22,
            "y": 696,
            "w": 20,
            "h": 31,
            "i": "scientificName",
            "style": null,
            "templateId": 1
          },
          {
            "id": 24,
            "tagName": "catalogue",
            "tagBefore": "Catálogo ",
            "tagAfter": ":",
            "model": "datacard",
            "modelAttribute": "catalogue.name",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "right",
            "backgroundColor": "rgba(28, 233, 181, 0.8)",
            "exampleValue": "Mamíferos",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 54,
            "y": 696,
            "w": 19,
            "h": 35,
            "i": "catalogue",
            "style": null,
            "templateId": 1
          },
          {
            "id": 25,
            "tagName": "code",
            "tagBefore": "",
            "tagAfter": "",
            "model": "datacard",
            "modelAttribute": "code",
            "fontSize": "20",
            "fontWeight": "normal",
            "fontStyle": "normal",
            "fontColor": null,
            "textAlignment": "right",
            "backgroundColor": "rgba(32, 148, 243, 0.8)",
            "exampleValue": "IIBUV-MAM 00001f",
            "draggable": 1,
            "resizable": 1,
            "isStatic": 0,
            "x": 73,
            "y": 696,
            "w": 17,
            "h": 35,
            "i": "code",
            "style": null,
            "templateId": 1
          }
        ]
      );
    });
};

